import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'ar' | 'tn';
export type Theme = 'light' | 'dark';

export interface LanguageThemeContextType {
  language: Language;
  theme: Theme;
  setLanguage: (lang: Language) => void;
  toggleTheme: () => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    logo: 'Invly',
    features: 'Features',
    templates: 'Templates',
    pricing: 'Pricing',
    logout: 'Logout',
    signin: 'Sign In',
    create_account: 'Create Account',
    back_home: 'Back Home',
    back_to_templates: 'Back to templates',
    view_homepage: 'View homepage',
    hero_badge: 'AI-powered invitation experiences',
    hero_title: 'Launch unforgettable invites for every milestone.',
    hero_desc: 'Create beautiful invitation experiences, personalize them for every guest, and share unique links instantly.',
    start_free: 'Start free',
    browse_templates: 'Browse templates',
    no_card: 'No credit card required',
    mobile_responsive: 'Mobile responsive',
    side_badge: 'Make it yours',
    side_title: 'Pick a polished template and personalize it instantly.',
    side_desc: 'Every layout is designed to feel elegant on desktop and mobile, with flexible content blocks for your story, timeline, and RSVP details.',
    side_bullet_1: 'Beautiful cover layouts with rich imagery',
    side_bullet_2: 'Custom content editor for event details',
    side_bullet_3: 'Share-ready invitation pages for every guest',
    see_all_templates: 'See all templates',
    feat_title: 'Visual Builder',
    feat_desc: 'Drag, drop, edit, and preview rich invitation layouts with modern controls.',
    feat2_title: 'Guest Personalization',
    feat2_desc: 'Generate tailored invites for each guest with unique links and QR codes.',
    feat3_title: 'Secure by Design',
    feat3_desc: 'Protect your data with encrypted sessions, role-based access, and audited actions.',
    pop_title: 'Popular Templates',
    pop_subtitle: 'Built for every category',
    featured: 'Featured',
    see_example: 'See example',
    footer_text: '© 2026 Invly. Built for modern events.',
    explore_title: 'Explore every invitation style',
    explore_desc: 'Filter by occasion and open the one that fits your celebration best.',
    all_templates: 'All templates',
    all_systems: 'All systems ready',
    drafts: 'Drafts',
    published: 'Published',
    guests: 'Guests',
    drafts_desc: 'Ready for final review.',
    published_desc: 'Live invitations across channels.',
    guests_desc: 'Personalized invites and trackers.',
    google_signin: 'Continue with Google',
    or: 'OR',
    email: 'Email address',
    password: 'Password',
    remember_me: 'Keep me signed in',
    signing_in: 'Signing in…',
    fullname: 'Full name',
    phone: 'Phone number',
    confirm_password: 'Confirm password',
    creating_account: 'Creating account…',
    create_account_btn: 'Create account',
    our_wedding_day: 'Our Wedding Day',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    event_details: 'Event Details',
    google_map: 'Google Map',
    wishes: 'Wishes',
    wishes_desc: 'A few heartfelt messages from those who love and support this beautiful celebration.',
    tap_to_open: 'Tap to open',
    hide_editor: 'Hide editor',
    edit_content: 'Edit content',
    invitation_builder: 'Invitation Builder',
    edit_the_invitation: 'Edit the invitation',
    reset: 'Reset',
    live_preview: 'Live preview',
    primary_names: 'Primary names',
    intro_label: 'Intro label',
    subtitle: 'Subtitle',
    date_time: 'Date & time',
    main_desc: 'Main description',
    page_colors: 'Page colors',
    bg_page: 'Page background',
    env_top: 'Envelope top',
    env_mid: 'Envelope middle',
    env_bot: 'Envelope bottom',
    border: 'Border',
    accent: 'Accent',
    text_primary: 'Primary text',
    text_secondary: 'Secondary text',
    lbl_text: 'Label text',
    story_tl: 'Story timeline',
    event_tl: 'Event timeline',
    add_event: 'Add event',
    remove: 'Remove',
    add_wish: 'Add wish',
    category_all: 'All',
    category_wedding: 'Wedding',
    category_birthday: 'Birthday',
    category_graduation: 'Graduation',
    category_business: 'Business',
    category_conference: 'Conference',
    category_ramadan: 'Ramadan',
    category_eid: 'Eid',
    category_custom: 'Custom',
    // Template descriptions (for templates page)
    tpl_twain_title: 'Twain Love Wedding',
    tpl_twain_subtitle: 'First template from wedinf temp 1',
    tpl_twain_desc: 'A romantic wedding invitation experience with elegant typography, love story moments, and RSVP details.',
    tpl_ej_title: 'Emma & James Wedding',
    tpl_ej_subtitle: 'A beautifully animated wedding invitation with story, gallery, countdown, and RSVP.',
    tpl_ej_desc: 'A fully integrated wedding invitation page with slideshow gallery and animated countdown.',
    tpl_golden_title: 'Golden Glow',
    tpl_golden_subtitle: 'Elegant warm tones with RSVP and countdown blocks.',
    tpl_golden_desc: 'A polished golden invitation layout for classic celebrations.',
    tpl_bloom_title: 'Modern Bloom',
    tpl_bloom_subtitle: 'Bright playful design with social handles and event details.',
    tpl_bloom_desc: 'A joyful, modern invitation layout for birthdays and personal events.',
    tpl_corp_title: 'Corporate Luxe',
    tpl_corp_subtitle: 'Premium event layout for conferences and presentations.',
    tpl_corp_desc: 'A refined layout for professional launches and high-end events.',
    tpl_midnight_title: 'Midnight Gala',
    tpl_midnight_subtitle: 'Luxury-inspired invitation experience for evening events.',
    tpl_midnight_desc: 'A glamorous invitation experience for evening galas and upscale celebrations.',
    // Emma & James wedding template translations
    ej_getting_married: 'We Are Getting Married',
    ej_our_love_story: 'Our Love Story',
    ej_the_big_day: 'The Big Day',
    ej_the_venue: 'The Venue',
    ej_location: 'Location',
    ej_get_directions: 'Get Directions',
    ej_gallery: 'Gallery',
    ej_schedule: 'Schedule',
    ej_dress_code: 'Dress Code',
    ej_dress_code_desc: 'Black Tie Optional',
    ej_join_celebration: 'Join Our Celebration',
    ej_rsvp_desc: 'Please let us know if you can make it to our special day.',
    ej_rsvp_now: 'RSVP Now',
    ej_thank_you: 'Thank you for sharing in our joy',
    ej_with_love: 'With love,',
    ej_days: 'Days',
    ej_hours: 'Hours',
    ej_minutes: 'Minutes',
    ej_seconds: 'Seconds',
    ej_we_met: 'We Met',
    ej_we_met_desc: 'The beginning of our beautiful journey together',
    ej_fell_in_love: 'We Fell in Love',
    ej_fell_in_love_desc: 'Every moment became more precious',
    ej_the_proposal: 'The Proposal',
    ej_the_proposal_desc: 'The moment we decided forever starts now',
    ej_now_celebrate: 'Now We Celebrate',
    ej_now_celebrate_desc: 'Surrounded by everyone we love',
    ej_guests_arrival: 'Guests Arrival',
    ej_ceremony_begins: 'Ceremony Begins',
    ej_reception_dinner: 'Reception & Dinner',
    ej_toasts_dancing: 'Toasts & Dancing',
    ej_send_off: 'Send Off',
    ej_bride_name: 'Bride Name',
    ej_groom_name: 'Groom Name',
    ej_wedding_date: 'Wedding Date',
    ej_wedding_time: 'Wedding Time',
    ej_venue_name: 'Venue Name',
    ej_venue_address: 'Venue Address',
    ej_maps_url: 'Maps URL',
    ej_love_story: 'Love Story',
    ej_bride_image: 'Bride Image',
    ej_groom_image: 'Groom Image',
    ej_color_primary: 'Primary',
    ej_color_secondary: 'Secondary',
    ej_countdown_enabled: 'Show Countdown',
    ej_music_url: 'Music URL',
  },
  fr: {
    logo: 'Invly',
    features: 'Fonctionnalités',
    templates: 'Modèles',
    pricing: 'Tarification',
    logout: 'Déconnexion',
    signin: 'Se connecter',
    create_account: 'Créer un compte',
    back_home: 'Retour à l\'accueil',
    back_to_templates: 'Retour aux modèles',
    view_homepage: 'Page d\'accueil',
    hero_badge: 'Des invitations propulsées par l\'IA',
    hero_title: 'Lancez des invitations inoubliables pour chaque étape.',
    hero_desc: 'Créez de superbes expériences d\'invitation, personnalisez-les pour chaque invité et partagez des liens uniques instantanément.',
    start_free: 'Commencer gratuitement',
    browse_templates: 'Parcourir les modèles',
    no_card: 'Aucune carte de crédit requise',
    mobile_responsive: 'Adapté aux mobiles',
    side_badge: 'Personnalisez-le',
    side_title: 'Choisissez un modèle soigné et personnalisez-le instantanément.',
    side_desc: 'Chaque mise en page est conçue pour être élégante sur ordinateur et mobile, avec des blocs de contenu flexibles pour votre histoire, votre calendrier et vos détails d\'invitation.',
    side_bullet_1: 'De superbes couvertures avec des images riches',
    side_bullet_2: 'Éditeur de contenu personnalisé pour les détails',
    side_bullet_3: 'Pages d\'invitations prêtes à partager pour chaque invité',
    see_all_templates: 'Voir tous les modèles',
    feat_title: 'Constructeur visuel',
    feat_desc: 'Glissez, déposez, modifiez et prévisualisez de superbes invitations avec des contrôles modernes.',
    feat2_title: 'Personnalisation des invités',
    feat2_desc: 'Générez des invitations personnalisées pour chaque invité avec des liens uniques et des codes QR.',
    feat3_title: 'Sécurisé par conception',
    feat3_desc: 'Protégez vos données avec des sessions chiffrées, des accès par rôles et des actions auditées.',
    pop_title: 'Modèles populaires',
    pop_subtitle: 'Conçu pour chaque catégorie',
    featured: 'En vedette',
    see_example: 'Voir l\'exemple',
    footer_text: '© 2026 Invly. Conçu pour les événements modernes.',
    explore_title: 'Explorez tous les styles d\'invitation',
    explore_desc: 'Filtrez par occasion et ouvrez celle qui convient le mieux à votre fête.',
    all_templates: 'Tous les modèles',
    all_systems: 'Tous les systèmes sont prêts',
    drafts: 'Brouillons',
    published: 'Publié',
    guests: 'Invités',
    drafts_desc: 'Prêt pour la révision finale.',
    published_desc: 'Invitations en direct sur tous les canaux.',
    guests_desc: 'Invitations personnalisées et suivis.',
    google_signin: 'Continuer avec Google',
    or: 'OU',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    remember_me: 'Rester connecté',
    signing_in: 'Connexion…',
    fullname: 'Nom complet',
    phone: 'Numéro de téléphone',
    confirm_password: 'Confirmer le mot de passe',
    creating_account: 'Création du compte…',
    create_account_btn: 'Créer un compte',
    our_wedding_day: 'Notre Jour de Mariage',
    days: 'Jours',
    hours: 'Heures',
    minutes: 'Minutes',
    seconds: 'Secondes',
    event_details: 'Détails de l\'événement',
    google_map: 'Carte Google',
    wishes: 'Vœux',
    wishes_desc: 'Quelques messages sincères de ceux qui aiment et soutiennent cette belle célébration.',
    tap_to_open: 'Appuyez pour ouvrir',
    hide_editor: 'Masquer l\'éditeur',
    edit_content: 'Modifier le contenu',
    invitation_builder: 'Constructeur d\'invitation',
    edit_the_invitation: 'Modifier l\'invitation',
    reset: 'Réinitialiser',
    live_preview: 'Aperçu en direct',
    primary_names: 'Noms principaux',
    intro_label: 'Étiquette d\'intro',
    subtitle: 'Sous-titre',
    date_time: 'Date & heure',
    main_desc: 'Description principale',
    page_colors: 'Couleurs de la page',
    bg_page: 'Arrière-plan',
    env_top: 'Enveloppe haut',
    env_mid: 'Enveloppe milieu',
    env_bot: 'Enveloppe bas',
    border: 'Bordure',
    accent: 'Accentuation',
    text_primary: 'Texte principal',
    text_secondary: 'Texte secondaire',
    lbl_text: 'Texte de l\'étiquette',
    story_tl: 'Chronologie de l\'histoire',
    event_tl: 'Déroulement de l\'événement',
    add_event: 'Ajouter événement',
    remove: 'Supprimer',
    add_wish: 'Ajouter vœu',
    category_all: 'Tout',
    category_wedding: 'Mariage',
    category_birthday: 'Anniversaire',
    category_graduation: 'Diplomation',
    category_business: 'Affaires',
    category_conference: 'Conférence',
    category_ramadan: 'Ramadan',
    category_eid: 'Aïd',
    category_custom: 'Personnalisé',
    // Template descriptions
    tpl_twain_title: 'Mariage Twain Love',
    tpl_twain_subtitle: 'Premier modèle de wedinf temp 1',
    tpl_twain_desc: 'Une expérience d\'invitation romantique avec une typographie élégante, des moments d\'histoire d\'amour et des détails RSVP.',
    tpl_ej_title: 'Mariage Emma & James',
    tpl_ej_subtitle: 'Une invitation de mariage animée avec histoire, galerie, compte à rebours et RSVP.',
    tpl_ej_desc: 'Une page d\'invitation de mariage entièrement intégrée avec galerie et compte à rebours animé.',
    tpl_golden_title: 'Éclat Doré',
    tpl_golden_subtitle: 'Tons chauds élégants avec RSVP et blocs de compte à rebours.',
    tpl_golden_desc: 'Un modèle d\'invitation doré et raffiné pour les célébrations classiques.',
    tpl_bloom_title: 'Floraison Moderne',
    tpl_bloom_subtitle: 'Design ludique et coloré avec réseaux sociaux et détails d\'événement.',
    tpl_bloom_desc: 'Un modèle d\'invitation joyeux et moderne pour les anniversaires et événements personnels.',
    tpl_corp_title: 'Luxe Corporate',
    tpl_corp_subtitle: 'Mise en page premium pour conférences et présentations.',
    tpl_corp_desc: 'Un modèle raffiné pour les lancements professionnels et événements haut de gamme.',
    tpl_midnight_title: 'Gala de Minuit',
    tpl_midnight_subtitle: 'Expérience d\'invitation luxueuse pour soirées.',
    tpl_midnight_desc: 'Une expérience d\'invitation glamour pour galas et célébrations de prestige.',
    // Emma & James wedding template
    ej_getting_married: 'Nous allons nous marier',
    ej_our_love_story: 'Notre Histoire d\'Amour',
    ej_the_big_day: 'Le Grand Jour',
    ej_the_venue: 'Le Lieu',
    ej_location: 'Emplacement',
    ej_get_directions: 'Obtenir l\'itinéraire',
    ej_gallery: 'Galerie',
    ej_schedule: 'Programme',
    ej_dress_code: 'Code Vestimentaire',
    ej_dress_code_desc: 'Tenue de soirée facultative',
    ej_join_celebration: 'Rejoignez notre célébration',
    ej_rsvp_desc: 'Veuillez nous faire savoir si vous pouvez assister à notre jour spécial.',
    ej_rsvp_now: 'Confirmer votre présence',
    ej_thank_you: 'Merci de partager notre joie',
    ej_with_love: 'Avec amour,',
    ej_days: 'Jours',
    ej_hours: 'Heures',
    ej_minutes: 'Minutes',
    ej_seconds: 'Secondes',
    ej_we_met: 'Notre rencontre',
    ej_we_met_desc: 'Le début de notre beau voyage ensemble',
    ej_fell_in_love: 'Nous sommes tombés amoureux',
    ej_fell_in_love_desc: 'Chaque moment est devenu plus précieux',
    ej_the_proposal: 'La Demande',
    ej_the_proposal_desc: 'Le moment où nous avons décidé que l\'éternité commence maintenant',
    ej_now_celebrate: 'Maintenant nous célébrons',
    ej_now_celebrate_desc: 'Entourés de tous ceux que nous aimons',
    ej_guests_arrival: 'Arrivée des invités',
    ej_ceremony_begins: 'Début de la cérémonie',
    ej_reception_dinner: 'Réception et dîner',
    ej_toasts_dancing: 'Toasts et danse',
    ej_send_off: 'Départ',
    ej_bride_name: 'Nom de la mariée',
    ej_groom_name: 'Nom du marié',
    ej_wedding_date: 'Date du mariage',
    ej_wedding_time: 'Heure du mariage',
    ej_venue_name: 'Nom du lieu',
    ej_venue_address: 'Adresse du lieu',
    ej_maps_url: 'URL de la carte',
    ej_love_story: 'Histoire d\'amour',
    ej_bride_image: 'Image de la mariée',
    ej_groom_image: 'Image du marié',
    ej_color_primary: 'Primaire',
    ej_color_secondary: 'Secondaire',
    ej_countdown_enabled: 'Afficher le compte à rebours',
    ej_music_url: 'URL de la musique',
  },
  ar: {
    logo: 'إينفلي',
    features: 'الميزات',
    templates: 'القوالب',
    pricing: 'الأسعار',
    logout: 'خروج',
    signin: 'دخول',
    create_account: 'حساب جديد',
    back_home: 'الرئيسية',
    back_to_templates: 'العودة للقوالب',
    view_homepage: 'الرئيسية',
    hero_badge: 'تجارب دعوة مدعومة بالذكاء الاصطناعي',
    hero_title: 'أطلق دعوات لا تُنسى لكل مناسبة.',
    hero_desc: 'أنشئ تجارب دعوة جميلة، وقم بتخصيصها لكل ضيف، وشارك روابط فريدة على الفور.',
    start_free: 'ابدأ مجاناً',
    browse_templates: 'تصفح القوالب',
    no_card: 'لا تتطلب بطاقة ائتمان',
    mobile_responsive: 'متوافق مع الهواتف',
    side_badge: 'اصنعها بنفسك',
    side_title: 'اختر قالبًا مصقولًا وقم بتخصيصه على الفور.',
    side_desc: 'تم تصميم كل تخطيط ليكون أنيقاً على الهاتف والكمبيوتر، مع كتل محتوى مرنة لقصتك، وجدولك الزمني، وتفاصيل الرد على الدعوة.',
    side_bullet_1: 'تخطيطات غلاف جميلة وصور غنية',
    side_bullet_2: 'محرر محتوى مخصص لتفاصيل الحدث',
    side_bullet_3: 'صفحات دعوة جاهزة للمشاركة لكل ضيف',
    see_all_templates: 'تصفح كل القوالب',
    feat_title: 'البناء البصري',
    feat_desc: 'اسحب، وأفلت، وحرر، وعاين تخطيطات دعوة غنية مع عناصر تحكم حديثة.',
    feat2_title: 'تخصيص الضيوف',
    feat2_desc: 'قم بإنشاء دعوات مخصصة لكل ضيف مع روابط فريدة ورموز QR.',
    feat3_title: 'الأمان المدمج',
    feat3_desc: 'احمِ بياناتك بجلسات مشفرة، وصلاحيات قائمة على الأدوار، وإجراءات مدققة.',
    pop_title: 'القوالب الشائعة',
    pop_subtitle: 'مصممة لكل فئة',
    featured: 'المميز',
    see_example: 'معاينة النموذج',
    footer_text: '© 2026 إينفلي. بني للفعاليات الحديثة.',
    explore_title: 'اكتشف كافة أنماط الدعوات',
    explore_desc: 'تصفية حسب المناسبة وافتح ما يناسب احتفالك تماماً.',
    all_templates: 'جميع القوالب',
    all_systems: 'جميع الأنظمة جاهزة',
    drafts: 'المسودات',
    published: 'المنشورة',
    guests: 'الضيوف',
    drafts_desc: 'جاهز للمراجعة النهائية.',
    published_desc: 'دعوات مباشرة عبر القنوات.',
    guests_desc: 'دعوات مخصصة لتتبع الضيوف.',
    google_signin: 'المتابعة باستخدام Google',
    or: 'أو',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    remember_me: 'تذكرني',
    signing_in: 'جاري تسجيل الدخول…',
    fullname: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    confirm_password: 'تأكيد كلمة المرور',
    creating_account: 'جاري إنشاء الحساب…',
    create_account_btn: 'إنشاء حساب',
    our_wedding_day: 'يوم زفافنا',
    days: 'أيام',
    hours: 'ساعات',
    minutes: 'دقائق',
    seconds: 'ثواني',
    event_details: 'تفاصيل الحدث',
    google_map: 'خريطة جوجل',
    wishes: 'الأمنيات',
    wishes_desc: 'بعض الرسائل القلبية من أولئك الذين يحبون ويدعمون هذا الاحتفال الجميل.',
    tap_to_open: 'انقر للفتح',
    hide_editor: 'إخفاء المحرر',
    edit_content: 'تعديل المحتوى',
    invitation_builder: 'منشئ الدعوات',
    edit_the_invitation: 'تعديل الدعوة',
    reset: 'إعادة ضبط',
    live_preview: 'معاينة مباشرة',
    primary_names: 'الأسماء الرئيسية',
    intro_label: 'نص المقدمة',
    subtitle: 'العنوان الفرعي',
    date_time: 'التاريخ والوقت',
    main_desc: 'الوصف الرئيسي',
    page_colors: 'ألوان الصفحة',
    bg_page: 'خلفية الصفحة',
    env_top: 'أعلى المظروف',
    env_mid: 'وسط المظروف',
    env_bot: 'أسفل المظروف',
    border: 'الإطار',
    accent: 'اللون التميزي',
    text_primary: 'النص الرئيسي',
    text_secondary: 'النص الفرعي',
    lbl_text: 'نص الملصق',
    story_tl: 'قصتنا',
    event_tl: 'جدول الحدث',
    add_event: 'إضافة حدث',
    remove: 'حذف',
    add_wish: 'إضافة أمنية',
    category_all: 'الكل',
    category_wedding: 'زفاف',
    category_birthday: 'عيد ميلاد',
    category_graduation: 'تخرج',
    category_business: 'أعمال',
    category_conference: 'مؤتمر',
    category_ramadan: 'رمضان',
    category_eid: 'عيد',
    category_custom: 'مخصص',
    // Template descriptions
    tpl_twain_title: 'زفاف توين لاف',
    tpl_twain_subtitle: 'القالب الأول من wedinf temp 1',
    tpl_twain_desc: 'تجربة دعوة زفاف رومانسية مع خط أنيق، لحظات قصة حب، وتفاصيل الرد على الدعوة.',
    tpl_ej_title: 'زفاف إيما وجيمس',
    tpl_ej_subtitle: 'دعوة زفاف متحركة بقصة ومعرض صور وعد تنازلي ورد على الدعوة.',
    tpl_ej_desc: 'صفحة دعوة زفاف متكاملة مع معرض صور متحرك وعد تنازلي.',
    tpl_golden_title: 'توهج ذهبي',
    tpl_golden_subtitle: 'ألوان دافئة أنيقة مع كتل RSVP والعد التنازلي.',
    tpl_golden_desc: 'تصميم دعوة ذهبي لامع للاحتفالات الكلاسيكية.',
    tpl_bloom_title: 'إزهار عصري',
    tpl_bloom_subtitle: 'تصميم مرح مع حسابات التواصل الاجتماعي وتفاصيل الحدث.',
    tpl_bloom_desc: 'تصميم دعوة مبهج وعصري لأعياد الميلاد والمناسبات الشخصية.',
    tpl_corp_title: 'فخامة الشركات',
    tpl_corp_subtitle: 'تصميم فاخر للمؤتمرات والعروض التقديمية.',
    tpl_corp_desc: 'تصميم راقي للإطلاقات المهنية والفعاليات الراقية.',
    tpl_midnight_title: 'حفلة منتصف الليل',
    tpl_midnight_subtitle: 'تجربة دعوة فاخرة للأمسيات.',
    tpl_midnight_desc: 'تجربة دعوة ساحرة لحفلات الغالا والاحتفالات الراقية.',
    // Emma & James wedding template
    ej_getting_married: 'نحن نتزوج',
    ej_our_love_story: 'قصة حبنا',
    ej_the_big_day: 'اليوم الكبير',
    ej_the_venue: 'المكان',
    ej_location: 'الموقع',
    ej_get_directions: 'الحصول على الاتجاهات',
    ej_gallery: 'معرض الصور',
    ej_schedule: 'البرنامج',
    ej_dress_code: 'قواعد اللباس',
    ej_dress_code_desc: 'لباس رسمي اختياري',
    ej_join_celebration: 'انضموا لاحتفالنا',
    ej_rsvp_desc: 'يرجى إعلامنا إذا كنتم ستحضرون يومنا المميز.',
    ej_rsvp_now: 'تأكيد الحضور',
    ej_thank_you: 'شكراً لمشاركتنا فرحتنا',
    ej_with_love: 'مع الحب،',
    ej_days: 'أيام',
    ej_hours: 'ساعات',
    ej_minutes: 'دقائق',
    ej_seconds: 'ثواني',
    ej_we_met: 'التقينا',
    ej_we_met_desc: 'بداية رحلتنا الجميلة معاً',
    ej_fell_in_love: 'وقعنا في الحب',
    ej_fell_in_love_desc: 'كل لحظة أصبحت أغلى',
    ej_the_proposal: 'الخطوبة',
    ej_the_proposal_desc: 'اللحظة التي قررنا فيها أن الأبدية تبدأ الآن',
    ej_now_celebrate: 'الآن نحتفل',
    ej_now_celebrate_desc: 'محاطين بكل من نحب',
    ej_guests_arrival: 'وصول الضيوف',
    ej_ceremony_begins: 'بداية الحفل',
    ej_reception_dinner: 'الاستقبال والعشاء',
    ej_toasts_dancing: 'الأنخاب والرقص',
    ej_send_off: 'الوداع',
    ej_bride_name: 'اسم العروس',
    ej_groom_name: 'اسم العريس',
    ej_wedding_date: 'تاريخ الزفاف',
    ej_wedding_time: 'وقت الزفاف',
    ej_venue_name: 'اسم المكان',
    ej_venue_address: 'عنوان المكان',
    ej_maps_url: 'رابط الخريطة',
    ej_love_story: 'قصة الحب',
    ej_bride_image: 'صورة العروس',
    ej_groom_image: 'صورة العريس',
    ej_color_primary: 'أساسي',
    ej_color_secondary: 'ثانوي',
    ej_countdown_enabled: 'إظهار العد التنازلي',
    ej_music_url: 'رابط الموسيقى',
  },
  tn: {
    // Tunisian Darija (Arabic Tunisian)
    logo: 'إينفلي',
    features: 'المميزات',
    templates: 'القوالب',
    pricing: 'الأسعار',
    logout: 'اخرج',
    signin: 'ادخل',
    create_account: 'حساب جديد',
    back_home: 'ارجع للدار',
    back_to_templates: 'ارجع للقوالب',
    view_homepage: 'الصفحة الرئيسية',
    hero_badge: 'دعوات بالذكاء الاصطناعي',
    hero_title: 'أطلق دعوات ما تتنساش لكل مناسبة.',
    hero_desc: 'اصنع تجارب دعوة بهية، خصصها لكل ضيف، وشارك روابط خاصة توّا.',
    start_free: 'ابدأ بلاش',
    browse_templates: 'تفرّج على القوالب',
    no_card: 'ما يلزمش كارت بنكية',
    mobile_responsive: 'يمشي على التليفون',
    side_badge: 'اصنعها كيما تحب',
    side_title: 'اختار قالب مزيان وخصصه توّا.',
    side_desc: 'كل تصميم مصمم بش يكون أنيق على الحاسوب والتليفون، مع كتل محتوى مرنة لقصتك وبرنامجك وتفاصيل الدعوة.',
    side_bullet_1: 'أغلفة بهية بصور ممتازة',
    side_bullet_2: 'محرر محتوى لتفاصيل الحدث',
    side_bullet_3: 'صفحات دعوة جاهزة للمشاركة لكل ضيف',
    see_all_templates: 'شوف الكل',
    feat_title: 'البناء البصري',
    feat_desc: 'جرّ، حطّ، عدّل، وشوف الدعوات مع أدوات عصرية.',
    feat2_title: 'تخصيص الضيوف',
    feat2_desc: 'اصنع دعوات مخصصة لكل ضيف بروابط خاصة و QR.',
    feat3_title: 'الأمان مضمون',
    feat3_desc: 'حمي بياناتك بجلسات مشفرة وصلاحيات وإجراءات مراقبة.',
    pop_title: 'القوالب المشهورة',
    pop_subtitle: 'مصممة لكل فئة',
    featured: 'المميز',
    see_example: 'شوف المثال',
    footer_text: '© 2026 إينفلي. مصنوع للأحداث العصرية.',
    explore_title: 'اكتشف كل أنماط الدعوات',
    explore_desc: 'فلتر بالمناسبة وافتح اللي يناسب حفلتك.',
    all_templates: 'القوالب الكل',
    all_systems: 'كل شي جاهز',
    drafts: 'المسودات',
    published: 'المنشورة',
    guests: 'الضيوف',
    drafts_desc: 'جاهز للمراجعة.',
    published_desc: 'دعوات حية في كل القنوات.',
    guests_desc: 'دعوات مخصصة وتتبع.',
    google_signin: 'كمّل بـ Google',
    or: 'ولا',
    email: 'البريد الإلكتروني',
    password: 'كلمة السر',
    remember_me: 'خليني داخل',
    signing_in: 'قاعد ندخل…',
    fullname: 'الاسم الكامل',
    phone: 'نمرة التليفون',
    confirm_password: 'عاود كلمة السر',
    creating_account: 'قاعد نصنع الحساب…',
    create_account_btn: 'اصنع حساب',
    our_wedding_day: 'يوم عرسنا',
    days: 'أيام',
    hours: 'سوايع',
    minutes: 'دقايق',
    seconds: 'ثواني',
    event_details: 'تفاصيل الحفلة',
    google_map: 'خريطة جوجل',
    wishes: 'التمنيات',
    wishes_desc: 'كلمات من القلب من الناس اللي يحبونا ويساندونا.',
    tap_to_open: 'اضغط بش تفتح',
    hide_editor: 'خبي المحرر',
    edit_content: 'عدّل المحتوى',
    invitation_builder: 'صانع الدعوات',
    edit_the_invitation: 'عدّل الدعوة',
    reset: 'رجّع للأصل',
    live_preview: 'معاينة مباشرة',
    primary_names: 'الأسامي الرئيسية',
    intro_label: 'نص المقدمة',
    subtitle: 'العنوان الفرعي',
    date_time: 'التاريخ والوقت',
    main_desc: 'الوصف الرئيسي',
    page_colors: 'ألوان الصفحة',
    bg_page: 'خلفية الصفحة',
    env_top: 'فوق المظروف',
    env_mid: 'وسط المظروف',
    env_bot: 'تحت المظروف',
    border: 'الإطار',
    accent: 'اللون المميز',
    text_primary: 'النص الرئيسي',
    text_secondary: 'النص الفرعي',
    lbl_text: 'نص الملصق',
    story_tl: 'قصتنا',
    event_tl: 'برنامج الحفلة',
    add_event: 'زيد حدث',
    remove: 'انحّي',
    add_wish: 'زيد أمنية',
    category_all: 'الكل',
    category_wedding: 'عرس',
    category_birthday: 'عيد ميلاد',
    category_graduation: 'تخرّج',
    category_business: 'أعمال',
    category_conference: 'مؤتمر',
    category_ramadan: 'رمضان',
    category_eid: 'عيد',
    category_custom: 'مخصص',
    // Template descriptions
    tpl_twain_title: 'عرس توين لاف',
    tpl_twain_subtitle: 'أول قالب من wedinf temp 1',
    tpl_twain_desc: 'تجربة دعوة عرس رومانسية بخط أنيق وقصة حب وتفاصيل الرد.',
    tpl_ej_title: 'عرس إيما وجيمس',
    tpl_ej_subtitle: 'دعوة عرس متحركة بقصة ومعرض صور وعد تنازلي.',
    tpl_ej_desc: 'صفحة دعوة عرس كاملة بمعرض صور وعد تنازلي متحرك.',
    tpl_golden_title: 'لمعة ذهبية',
    tpl_golden_subtitle: 'ألوان دافئة أنيقة مع RSVP وعد تنازلي.',
    tpl_golden_desc: 'تصميم دعوة ذهبي للاحتفالات الكلاسيكية.',
    tpl_bloom_title: 'إزهار عصري',
    tpl_bloom_subtitle: 'تصميم مرح بألوان حلوة وتفاصيل الحدث.',
    tpl_bloom_desc: 'تصميم دعوة مبهج لأعياد الميلاد والمناسبات.',
    tpl_corp_title: 'فخامة الشركات',
    tpl_corp_subtitle: 'تصميم فاخر للمؤتمرات.',
    tpl_corp_desc: 'تصميم راقي للفعاليات المهنية الكبيرة.',
    tpl_midnight_title: 'حفلة نص الليل',
    tpl_midnight_subtitle: 'تجربة دعوة فاخرة للسهرات.',
    tpl_midnight_desc: 'تجربة دعوة ساحرة لحفلات الغالا.',
    // Emma & James wedding template
    ej_getting_married: 'رانا نعرّسو',
    ej_our_love_story: 'قصة حبنا',
    ej_the_big_day: 'النهار الكبير',
    ej_the_venue: 'البلاصة',
    ej_location: 'الموقع',
    ej_get_directions: 'شوف الطريق',
    ej_gallery: 'معرض الصور',
    ej_schedule: 'البرنامج',
    ej_dress_code: 'اللبسة المطلوبة',
    ej_dress_code_desc: 'لبسة رسمية اختيارية',
    ej_join_celebration: 'اجي احتفل معانا',
    ej_rsvp_desc: 'عطينا خبر كان تنجم تجي لنهارنا الكبير.',
    ej_rsvp_now: 'أكّد الحضور',
    ej_thank_you: 'شكراً على المشاركة في فرحتنا',
    ej_with_love: 'بالحب،',
    ej_days: 'أيام',
    ej_hours: 'سوايع',
    ej_minutes: 'دقايق',
    ej_seconds: 'ثواني',
    ej_we_met: 'تقابلنا',
    ej_we_met_desc: 'بدات رحلتنا البهية مع بعض',
    ej_fell_in_love: 'حبينا بعضنا',
    ej_fell_in_love_desc: 'كل لحظة ولات أغلى',
    ej_the_proposal: 'الخطوبة',
    ej_the_proposal_desc: 'اللحظة اللي قررنا فيها أن الأبدية تبدا توّا',
    ej_now_celebrate: 'توّا نحتفلو',
    ej_now_celebrate_desc: 'محاطين بكل الناس اللي نحبوهم',
    ej_guests_arrival: 'وصول الضيوف',
    ej_ceremony_begins: 'بداية الحفل',
    ej_reception_dinner: 'الاستقبال والعشاء',
    ej_toasts_dancing: 'التوستات والرقص',
    ej_send_off: 'التوديع',
    ej_bride_name: 'اسم العروسة',
    ej_groom_name: 'اسم العريس',
    ej_wedding_date: 'تاريخ العرس',
    ej_wedding_time: 'وقت العرس',
    ej_venue_name: 'اسم البلاصة',
    ej_venue_address: 'عنوان البلاصة',
    ej_maps_url: 'رابط الخريطة',
    ej_love_story: 'قصة الحب',
    ej_bride_image: 'صورة العروسة',
    ej_groom_image: 'صورة العريس',
    ej_color_primary: 'أساسي',
    ej_color_secondary: 'ثانوي',
    ej_countdown_enabled: 'ورّي العد التنازلي',
    ej_music_url: 'رابط الموسيقى',
  },
};

const LanguageThemeContext = createContext<LanguageThemeContextType | undefined>(undefined);

export const LanguageThemeProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('invly-lang');
    return (saved === 'fr' || saved === 'ar' || saved === 'tn') ? saved : 'en';
  });

  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = localStorage.getItem('invly-theme');
    return saved === 'light' ? 'light' : 'dark'; // Dark is default
  });

  useEffect(() => {
    // Sync language attributes
    const isRtl = language === 'ar' || language === 'tn';
    document.documentElement.dir = isRtl ? 'rtl' : 'ltr';
    document.documentElement.lang = language === 'tn' ? 'ar-TN' : language;
    localStorage.setItem('invly-lang', language);
  }, [language]);

  useEffect(() => {
    // Sync theme class
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
      root.style.colorScheme = 'dark';
    } else {
      root.classList.remove('dark');
      root.style.colorScheme = 'light';
    }
    localStorage.setItem('invly-theme', theme);
  }, [theme]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const toggleTheme = () => {
    setThemeState((prev) => (prev === 'dark' ? 'light' : 'dark'));
  };

  const t = (key: string): string => {
    const translationSet = translations[language];
    return translationSet[key] || translations['en'][key] || key;
  };

  const isRtl = language === 'ar' || language === 'tn';

  return (
    <LanguageThemeContext.Provider value={{ language, theme, setLanguage, toggleTheme, t, isRtl }}>
      {children}
    </LanguageThemeContext.Provider>
  );
};

export const useLanguageTheme = () => {
  const context = useContext(LanguageThemeContext);
  if (!context) {
    throw new Error('useLanguageTheme must be used within a LanguageThemeProvider');
  }
  return context;
};
